### ISSUE TITLE
Another way of using icons

### ISSUE THREAD

**Issue by hiradary** [jrgarciadev/react-iconly#1]
Hi Junior!

Thanks for your amazing work. I'm a co-founder in Piqo, and we're launching a presentation website/landing page for Iconly.
I used your package to showcase the icons, just like the way you did on https://react-iconly.jrgarciadev.com/.

However, I suppose there's a better way to use Iconly in the project. Currently, you have to do something like this:

```javascript
import { Search } from 'react-iconly'
```

I'm wondering if we could do like this:

```javascript
import Iconly from 'react-iconly'

const MyComponent = () => {
  return (
    <Iconly name="search" set="light" />
  )
}
```

Or a combination of default & named exports:

```javascript
import Iconly, { Search } from 'react-iconly';
```
I decided to do it my self in my forked version of react-iconly here https://github.com/hiradary/react-iconly/blob/main/src/index.js, but I ran into some problems regarding building & using it in my project.

Also I thought It'd be better if you could implement this, so others could also benefit.

**Comment by jrgarciadev** [comment]
Hi @hiradary!

Thanks to you for your amazing work designing Iconly.

I agree with you, I'm going to add your suggestion. What kind of problems did you have running the project?

**Comment by hiradary** [comment]
For example, I want to list all icons like this:

```javascript
import Iconly from 'react-iconly';

const ICONS = [
  {
    name: 'Search',
  },
  {
    name: 'Chat',
  },
  {
    name: 'Ticket',
  },
]

const MyComponent = () => {
  return (
    <div>
      {ICONS.map((item) => (
        <Iconly name={item.name} set="light" />
      )}
    <div>
  )
}
```

Otherwise, I have to first import 100 Icons, then assign each one of them to an array. It'll add 200 lines to my codebase.
This way I only need to add 100 lines.

**Comment by hiradary** [comment]
I suppose It's a cleaner syntax as well.

**Comment by jrgarciadev** [comment]
@hiradary here the solution: https://github.com/jrgarciadev/react-iconly/commit/333f30e3711df275ddcf9d00251098c6a5ac40ca

**Comment by jrgarciadev** [comment]
@hiradary Let I know if you agree with that to implement the new version

**Comment by hiradary** [comment]
@jrgarciadev Thanks for the fast response! the API seems pretty cool!

**Comment by jrgarciadev** [comment]
You're welcome!, I'm going to publish the new version 🚀
