### ISSUE TITLE
Icon request - Not really an issue.

### ISSUE THREAD

**Issue by ynnelson** [jrgarciadev/react-iconly#11]
You icons are fantastics, no idea if you plan and expanding the current set but some icons that would be great to add:

- hashtag
- hamburger menu
- 3 dot menu without border
- reply all
- forward
- cloud
- paperclip / attachment
- refresh / sync
- plus without border
- minus without border

This is very self serving obviously but you're icons are so good I figured I'd ask :)
K  I am done!

Great work!

**Comment by jrgarciadev** [comment]
Hey @ynnelson thank you so much, I could relay your request to the company behind Iconly icons, I've only made de react library for that great pack so I'm not able to release new icons, here is the original pack https://piqodesign.gumroad.com/l/iconly
