### ISSUE TITLE
No support for Vite/Typescript

### ISSUE THREAD

**Issue by SalahAdDin** [jrgarciadev/react-iconly#14]
Hello, thanks for your package

I wanted to user this package as icon provider, but I am getting this error with **Vite**:
```
Uncaught ReferenceError: process is not defined
    s2 factoryWithTypeCheckers.js:170
    i2 factoryWithTypeCheckers.js:241
    exports factoryWithTypeCheckers.js:116
    Q index.js:9
    u context.js:34
    <anonymous> factoryWithThrowingShims.js:16

```

Why?

I also want to ask for `Plug` and `List`  icons.

Thanks

**Comment by Brandyweb** [comment]
You can fix add define in your vite.config.ts

```javascript
export default defineConfig({
  ...
  define: {
    'process.env': {},
  }
});
```

**Comment by rivaslive** [comment]
You can fix add define in your vite.config.ts
```javascript
export default defineConfig({
  ...
  define: {
    'process.env': {},
  }
});
```

**Comment by SalahAdDin** [comment]
> You can fix add define in your vite.config.ts
> 
> ```js
> export default defineConfig({
>   ...
>   define: {
>     'process.env': {},
>   }
> });
> ```

Yeah, it worked for me, but, why?

**Comment by rivaslive** [comment]
@SalahAdDin Vitejs not use `process.env` not exist in the environment Vitejs use `import.meta.env` then we're resolving the `process.env` like a object empty

More info of Vitejs => https://vitejs.dev/guide/env-and-mode.html
