### ISSUE TITLE
Error: process is not defined

### ISSUE THREAD

**Issue by sagarsoni7** [jrgarciadev/react-iconly#18]
My React version is 17

**Comment by sagarsoni7** [comment]
Temp fix

https://stackoverflow.com/a/64553486/2811107

**Comment by adexzy1** [comment]
facing this same issue in my project

factoryWithTypeCheckers.js:170 Uncaught ReferenceError: process is not defined
    at s (factoryWithTypeCheckers.js:170:1)
    at i (factoryWithTypeCheckers.js:241:1)
    at factoryWithTypeCheckers.js:116:1
    at index.js:14:1
    at u (context.js:34:1)
    at Module../node_modules/react-iconly/dist/index.modern.js (factoryWithThrowingShims.js:16:1)
    at Module.options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:61:1)
    at Module../src/components/DashboardNav.jsx (AdminDashboard.jsx:5:1)
s @ factoryWithTypeCheckers.js:170
i @ factoryWithTypeCheckers.js:241
(anonymous) @ factoryWithTypeCheckers.js:116
(anonymous) @ index.js:14
u @ context.js:34
./node_modules/react-iconly/dist/index.modern.js @ factoryWithThrowingShims.js:16
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
fn @ hot module replacement:61
./src/components/DashboardNav.jsx @ AdminDashboard.jsx:5
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
fn @ hot module replacement:61
./src/pages/Dashboard.jsx @ index.js:7
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
fn @ hot module replacement:61
./src/App.js @ bundle.js:21
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
fn @ hot module replacement:61
./src/index.js @ SignUpStep2.jsx:48
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
(anonymous) @ startup:7
(anonymous) @ startup:7

**Comment by AndreyVozniuk** [comment]
Yeap, me too, the same issue.

I am using react-scripts: 5.0.0 version and 17 version of React.

**Comment by iperezluis** [comment]
I've the same issue in my react project, but i still not find the solution

**Comment by ionleu** [comment]
Potential fix here: #33, please test it and let me know if works as expected.

**Comment by MiladPashaei** [comment]
> Potential fix here: #33, please test it and let me know if works as expected.

your PR didn't merge correctly, you can check your PR changes and current state of repository in package.json .

**Comment by ionleu** [comment]
@MiladPashaei try to downgrade `react-scripts` package from your project to `4.0.3`, until a fix will be provided.
