### ISSUE TITLE
Website error: Cant show icons

### ISSUE THREAD

**Issue by stefanosandes** [jrgarciadev/react-iconly#19]
The web site is gettin an error from algolia api: 

```
{"message":"Operations quota exceeded. Change plan to get more Operations.","status":403}
```

**Comment by mohammadshariat** [comment]
Yes I Have This Problem Too  And I Cant See Any Icon At The WebSite

**Comment by jrgarciadev** [comment]
Hey @stefanosandes @mohammadshariat sorry for this, I will contact the Algolia Team in order to try to get the `Open source` quota plan

**Comment by bineetNaidu** [comment]
Hey, am I still facing this problem on your website :smiley:

**Comment by jrgarciadev** [comment]
Hey @bineetNaidu yeah sorry the Algolia team is still processing my request about then Open source monthly plan

**Comment by jrgarciadev** [comment]
Hey @stefanosandes , I wrote to the Algolia team several times to get the open-source plan but didn't get a reply. I had to pay the monthly plan. Is working now 👍🏻
