### ISSUE TITLE
Error: ReactDOMServer does not yet support Suspense.

### ISSUE THREAD

**Issue by hiradary** [jrgarciadev/react-iconly#2]
Hey Junior!

I'm getting this in `v1.1.0`. It seems to be produced due to this commit: https://github.com/jrgarciadev/react-iconly/commit/333f30e3711df275ddcf9d00251098c6a5ac40ca

**My dependencies:**
```javascript
"next": "10.0.3",
"react": "17.0.1",
"react-dom": "17.0.1",
"react-iconly": "^1.1.0",
```

**Error:**
![Screen Shot 2020-12-27 at 4 07 36 PM](https://user-images.githubusercontent.com/29271309/103171035-33e98600-485e-11eb-8de6-89d356fa17c6.png)

**Steps to reproduce:**
Setup a project with the above dependencies.

**Comment by jrgarciadev** [comment]
Hi, @hiradary thanks for reporting,

Already solved this issue, please install version v1.1.1

**Comment by jrgarciadev** [comment]
Hey @hiradary, did it work for you? to close the issue 🙋🏻‍♂️

**Comment by hiradary** [comment]
Yup, Thanks! I'm gonna be closing the issue.
