### ISSUE TITLE
blank page when I use iconly

### ISSUE THREAD

**Issue by LorenzoRu** [jrgarciadev/react-iconly#25]
Hello, when i use iconly i have a blank page and i don't know why. Furthermore when i use npm to install there is some error. How i can fix this ?

Thanks for your help 😄

**Comment by LorenzoRu** [comment]
i use react 18.1.0 with mui

**Comment by jrgarciadev** [comment]
Hey @LorenzoRu thanks for reporting it, It looks like I have to update the library to support react 18

**Comment by husinzz** [comment]
hello has this been fix? cause im having the same problem, if not is there a work around i could do?

**Comment by felipe-miranda-marreiros** [comment]
> hello has this been fix? cause im having the same problem, if not is there a work around i could do?

You can use unplugin-icons. Download the icons you want and set them in your src folder. Then use unplugin-icons with FileSystemIconLoader. It will load all svgs globally.

You can also create different approaches with unplugin-icons using customCollections like ~iconly-bold or ~iconly-light.

**Comment by SalahAdDin** [comment]
@jrgarciadev what do you think about this?
