### ISSUE TITLE
[BUG] Website does not load icons

### ISSUE THREAD

**Issue by DannyNemer** [jrgarciadev/react-iconly#26]
## No icons load when visiting https://react-iconly.jrgarciadev.com:
![image](https://user-images.githubusercontent.com/170023/169168103-b952cdde-0515-41c0-a213-c0de45c6c99a.png)

## Nothing loads for any input in the search bar:
<img width="1381" alt="image" src="https://user-images.githubusercontent.com/170023/169168189-6bb08e38-6c10-4c74-8bec-9003a7a6012f.png">

## There are a bunch of request errors (I tested this in Chrome and Safar with adblockers disabled):
<img width="702" alt="image" src="https://user-images.githubusercontent.com/170023/169168280-cbb10211-8e05-4600-a20f-47e8e953ac92.png">

**Comment by jrgarciadev** [comment]
Hey @DannyNemer  🙌🏻 , I wrote to the Algolia team several times to get the open-source plan but didn't get a reply. I had to pay the monthly plan. Is working now 👍🏻

**Comment by DannyNemer** [comment]
Thank you very much, @jrgarciadev!
