### ISSUE TITLE
Upgrade to React 18

### ISSUE THREAD

**Issue by conversun** [jrgarciadev/react-iconly#27]
<img width="894" alt="image" src="https://user-images.githubusercontent.com/22893221/173387502-891f55dc-7f47-4ab9-bb71-a178e1e1c219.png">

**Comment by ebukaodini** [comment]
Hi @jrgarciadev
I got this error while deploying to netlify. I'm using "react-iconly": "^2.2.5",

![image](https://user-images.githubusercontent.com/26033629/179796380-cfae8102-2dd3-4749-b8de-b04132ee731e.png)

**Comment by ayoubphy** [comment]
Is there any progress on this issue ?

**Comment by A1yks** [comment]
> Is there any progress on this issue ?

You can install this module with --force flag. After that you need to create a file _react-iconly.d.ts_ with the following contents:

```
import { ReactNode } from 'react';

declare module 'react-iconly' {
    export interface IconProps {
        children?: ReactNode;
    }
}
```

And don't forget to include this file in your _tsconfig.json_

**Comment by SalahAdDin** [comment]
@jrgarciadev man?

**Comment by 6km** [comment]
@jrgarciadev can you please give some attention to this issue?

**Comment by jrgarciadev** [comment]
Sorry guys but currently I'm focused on the `NextUI` migration to TailwindCSS so I have no time for updating this library at the moment,  if any of you want to send a PR migrating it to React 18 it will be appreciated 🙏🏻

**Comment by SalahAdDin** [comment]
> Sorry guys but currently I'm focused on the `NextUI` migration to TailwindCSS so I have no time for updating this library at the moment, if any of you want to send a PR migrating it to React 18 it will be appreciated 🙏🏻

I think you have no access to the last icons, right? In that case, we can't add more icons I think.
