### ISSUE TITLE
Some icons are missing/extra

### ISSUE THREAD

**Issue by hiradary** [jrgarciadev/react-iconly#3]
Iconly is a set of 500 icons (100 icons in 5 different styles). However, if you count the number of icons here:

https://react-iconly.jrgarciadev.com/

You'll see 101 icons. One icon seems to be extra.

Also, if you see the official list [here](https://www.figma.com/file/OIDDYEusFCk3YCCmTZua4r/Iconly-Library?node-id=0%3A750), you'll see the below icon which isn't listed on react-iconly page:

![Screen Shot 2020-12-29 at 5 23 33 PM](https://user-images.githubusercontent.com/29271309/103289088-9af07180-49fb-11eb-8f5c-816a4d798457.png)

![Screen Shot 2020-12-29 at 5 31 11 PM](https://user-images.githubusercontent.com/29271309/103289113-a774ca00-49fb-11eb-811a-5a0cb116f1df.png)

I think there are inconsistencies between the actual icon set and react-iconly, which is something quite important to fix.
I guess we should go through the icons one by one, to ensure there's no inconsistency between the two.

**Comment by jrgarciadev** [comment]
Hey @hiradary, it's listed with the **Chevron Down** name in the **bold** category.
 
<img width="997" alt="Screen Shot 2020-12-29 at 18 07 32" src="https://user-images.githubusercontent.com/30373425/103314084-bc079100-4a00-11eb-82fe-e098fb9e2a92.png">

One icon is extra because I added the "Heart" icon without inner line.
<img width="1065" alt="Screen Shot 2020-12-29 at 18 14 37" src="https://user-images.githubusercontent.com/30373425/103314412-c8401e00-4a01-11eb-9dc6-2c913ae007b1.png">

**Comment by hiradary** [comment]
@jrgarciadev  Got it!

There's one more thing to mention. We've got `PaperFail` and `ShieldFail` icons. It's mistakenly written as `PaperFall` in `mapIcons.js` file. https://github.com/jrgarciadev/react-iconly/blob/8fb31d1235a59eaac8423eb66a52075c07ef3b2d/src/lib/mapIcons.js#L19
https://github.com/jrgarciadev/react-iconly/blob/8fb31d1235a59eaac8423eb66a52075c07ef3b2d/src/lib/mapIcons.js#L73

The correct form is used in the website:
https://github.com/jrgarciadev/react-iconly/blob/8fb31d1235a59eaac8423eb66a52075c07ef3b2d/website/distIcons/tags.json#L163
https://github.com/jrgarciadev/react-iconly/blob/8fb31d1235a59eaac8423eb66a52075c07ef3b2d/website/distIcons/tags.json#L141

**Comment by jrgarciadev** [comment]
Hi @hiradary thanks for reporting, I already rename it here -> https://github.com/jrgarciadev/react-iconly/commit/fc70b8607ede83b7fc08c838056dfdadaf6d2ef2

**Comment by hiradary** [comment]
@jrgarciadev I found another issue on the website...

if you visit [here](https://react-iconly.jrgarciadev.com/) and select different sets such as two-tone and light, you'll see some sets contain less/more icons compared to the other ones. Whereas in the official pack, all sets contain 100 icons, nothing more or less. Here we should see 101 icons - considering the fact that you added another heart Icon.

**Comment by jrgarciadev** [comment]
@hiradary Thanks for reporting, I'm going to review the icons map generator script https://github.com/jrgarciadev/react-iconly/blob/main/website/scripts/generate-icons.js

**Comment by jrgarciadev** [comment]
Hi! @hiradary 

The missing icons were solved, it was a problem with the names that did not allow the generate-icons.js script to generate them correctly, for example in website/icons/light there was the icon "TicketStart" with the name "Ticket Star.svg" with space.

Also, I updated these icons on Algolia

Here the changes -> https://github.com/jrgarciadev/react-iconly/commit/9a94cbfb6c7798edecc724685810e0fb46800af5

**Comment by hiradary** [comment]
@jrgarciadev Great! Thanks.
