### ISSUE TITLE
Update package

### ISSUE THREAD

**Issue by hiradary** [jrgarciadev/react-iconly#6]
Hi @jrgarciadev!

Piqo Design Team has recently updated the Iconly icon set and added 100 more icons. There's a new `curved` style included in the new version.

You can find it here: https://gumroad.com/piqodesign

Please add these to the package.

Thanks ❤️

**Comment by jrgarciadev** [comment]
Hi @hiradary, sure I'm going to add those icons, Is there a AdobeXD version?

**Comment by hiradary** [comment]
@jrgarciadev Yeah sure, It's included.

**Comment by jrgarciadev** [comment]
Hi @hiradary, react-iconly v2.2.1 has been deployed with the new curved icons! 🚀
